[2022-06-04 12:55:39 +0800] [3321903] [INFO] Starting gunicorn 20.1.0
[2022-06-04 12:55:39 +0800] [3321903] [INFO] Listening at: http://127.0.0.1:8180 (3321903)
[2022-06-04 12:55:39 +0800] [3321903] [INFO] Using worker: gevent
[2022-06-04 12:55:39 +0800] [3321905] [INFO] Booting worker with pid: 3321905
[2022-06-04 12:55:39 +0800] [3321906] [INFO] Booting worker with pid: 3321906
[2022-06-04 12:55:39 +0800] [3321907] [INFO] Booting worker with pid: 3321907
[2022-06-04 12:55:39 +0800] [3321917] [INFO] Booting worker with pid: 3321917
[2022-06-04 12:57:06 +0800] [3321903] [WARNING] Worker with pid 3321905 was terminated due to signal 9
[2022-06-04 12:57:06 +0800] [3322930] [INFO] Booting worker with pid: 3322930
[2022-06-04 12:57:13 +0800] [3321903] [INFO] Handling signal: term
[2022-06-04 12:57:13 +0800] [3322930] [INFO] Worker exiting (pid: 3322930)
[2022-06-04 12:57:13 +0800] [3321907] [INFO] Worker exiting (pid: 3321907)
[2022-06-04 12:57:13 +0800] [3321906] [INFO] Worker exiting (pid: 3321906)
[2022-06-04 12:57:13 +0800] [3321917] [INFO] Worker exiting (pid: 3321917)
[2022-06-04 12:57:13 +0800] [3321903] [INFO] Shutting down: Master
[2022-06-04 12:57:31 +0800] [3323225] [INFO] Starting gunicorn 20.1.0
[2022-06-04 12:57:31 +0800] [3323225] [INFO] Listening at: http://127.0.0.1:8180 (3323225)
[2022-06-04 12:57:31 +0800] [3323225] [INFO] Using worker: gevent
[2022-06-04 12:57:31 +0800] [3323227] [INFO] Booting worker with pid: 3323227
[2022-06-04 12:57:31 +0800] [3323228] [INFO] Booting worker with pid: 3323228
[2022-06-04 12:57:31 +0800] [3323229] [INFO] Booting worker with pid: 3323229
[2022-06-04 12:57:31 +0800] [3323230] [INFO] Booting worker with pid: 3323230
[2022-06-04 12:58:48 +0800] [3324444] [INFO] Starting gunicorn 20.1.0
[2022-06-04 12:58:48 +0800] [3324444] [INFO] Listening at: http://127.0.0.1:8180 (3324444)
[2022-06-04 12:58:48 +0800] [3324444] [INFO] Using worker: gevent
[2022-06-04 12:58:48 +0800] [3324446] [INFO] Booting worker with pid: 3324446
[2022-06-04 12:58:48 +0800] [3324447] [INFO] Booting worker with pid: 3324447
[2022-06-04 12:58:48 +0800] [3324448] [INFO] Booting worker with pid: 3324448
[2022-06-04 12:58:48 +0800] [3324458] [INFO] Booting worker with pid: 3324458
[2022-06-05 02:56:58,642] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/16689611403'
[2022-06-05 02:58:58,925] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))[2022-06-05 03:10:08,417] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/13295140376'
[2022-06-05 03:13:57,147] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2022-06-05 02:59:14,380] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15117909871'
[2022-06-05 03:08:38,849] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15936588605'
[2022-06-05 03:13:58,136] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.

  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/13153483530'
[2022-06-05 03:13:58,704] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2022-06-05 03:15:36,886] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/13892039880'
[2022-06-05 03:26:40,463] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/13918378191'
[2022-06-05 03:44:47,215] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/18510481921'
[2022-06-05 03:46:39,878] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2022-06-05 03:18:14,851] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15114920008'
[2022-06-05 03:24:18,752] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/13689900199'
[2022-06-05 03:24:49,259] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/f[2022-06-05 04:19:04,745] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2022-06-05 03:08:03,783] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/16285447222'
[2022-06-05 03:25:20,526] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flasklask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/16791809555'
[2022-06-05 05:24:05,589] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2022-06-05 03:33:05,069] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15264464925'
[2022-06-05 03:41:51,920] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15100733688'
[2022-06-05 03:43:38,980] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15828403608'
[2022-06-05 05:24:05,937] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15237111543'
[2022-06-05 03:33:14,763] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15907226689'
[2022-06-05 05:24:06,184] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2022-06-05 04:50:55,126] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/17775301755'
[2022-06-05 04:53:00,093] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/15579507952'
[2022-06-05 05:21:54,031] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 182, in register
    filepath,speech_number = save_wav_from_url(new_url,new_spkid,cfg.REGISTER_RAW_PATH)
  File "/VAF-System/demo_flask/utils/save.py", line 51, in save_wav_from_url
    os.makedirs(spk_dir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
OSError: [Errno 28] No space left on device: './wavs/raw/13633322818'
[2022-06-05 05:24:07,664] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 1451, in set
    return self.execute_command('SET', *pieces)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[2022-06-05 05:24:14,367] ERROR in app: Exception on /register/url [POST]
Traceback (most recent call last):
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lyxx/.local/lib/python3.8/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/VAF-System/demo_flask/vvs_service.py", line 272, in register
    add_success,phone_info = add_to_database(
  File "/VAF-System/demo_flask/utils/database.py", line 65, in add_to_database
    toRedis(r,embedding_npy,f'{max_class_index}_{spkid}')
  File "/VAF-System/demo_flask/utils/database.py", line 22, in toRedis
    r.set(n,encoded)
  File "/home/lyxx/.local/lib/python3.8/site-packages/redis/client.